name: prepare-release

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  update-version-in-pr:
    if: startsWith(github.head_ref, 'release-please--')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT_RELEASE_PLEASE }}

      - name: Determine release version
        run: |
          VERSION=$(jq -r '.["."]' .github/release-please/manifest.json 2>/dev/null)

          if [[ -z "$VERSION" || "$VERSION" == "null" ]]; then
            echo "::error::Unable to determine release version"
            exit 1
          fi

          if git log -1 --pretty=%s | grep -q "^chore: bump v${VERSION} on files$"; then
            echo "Version bump already applied."
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "Version bump required: $VERSION"
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          fi
        id: version_check

      - name: Bump version
        run: |
          php ./src/joomla/build/bump.php -v ${{ steps.version_check.outputs.version }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: bump v${{ steps.version_check.outputs.version }} on files"
