name: prepare-release

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update-version-in-pr:
    if: startsWith(github.head_ref, 'release-please--')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - run: |
          NEW_VERSION=$(jq -r '."src/joomla"' .release-please-manifest.json)
          OLD_VERSION=$(git show origin/${{ github.base_ref }}:.release-please-manifest.json | jq -r '."src/joomla"')

          echo "Versão na Main: $OLD_VERSION"
          echo "Versão no PR: $NEW_VERSION"

          if [ "$NEW_VERSION" != "$OLD_VERSION" ] && [ "$NEW_VERSION" != "null" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
        id: version_check

      - if: ${{ steps.version_check.outputs.changed == 'true' }}
        run: |
          php ./src/joomla/build/bump.php -v ${{ steps.version_check.outputs.version }}

      - uses: stefanzweifel/git-auto-commit-action@v7
        if: ${{ steps.version_check.outputs.changed == 'true' }}
        with:
          commit_message: "chore: version bump ${{ steps.version_check.outputs.version }}"
